name:                         Rust cargo build and draft release

on:
  push:
    branches:
      - main

jobs:
  cargo-build:
    name:                     Cargo build
    runs-on:                  ubuntu-latest
    env:
      GH_TOKEN:               ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name:                 Cancel Previous Runs
        uses:                 styfle/cancel-workflow-action@0.12.1
        with:
          access_token:       ${{ github.token }}

      - name:                 Checkout sources
        uses:                 actions/checkout@v4.1.1
        with:
          fetch-depth:        50
          submodules:         'recursive'

      - name:                 Install Rust stable toolchain
        uses:                 actions-rs/toolchain@v1.0.7
        with:
          profile:            minimal
          toolchain:          stable
          override:           true

      - name:                 Rust Cache
        uses:                 Swatinem/rust-cache@v2.7.3

      - name:                 cargo build basic
        run:                  cargo build --release

      - name:                 Get basic package version
        run:                  >
                              echo "VERSION=$(
                              cargo metadata --format-version=1 --no-deps |
                              jq -r '.packages[] | select(.name == "kalatori") | .version'
                              )" >> $GITHUB_ENV

      - name:                 cargo build ah
        run:                  cargo build --release --manifest-path=./kalatori-ah/Cargo.toml

      - name:                 Get ah package version
        run:                  >
                              echo "AH_VERSION=$(
                              cargo metadata
                              --format-version=1
                              --no-deps
                              --manifest-path=./kalatori-ah/Cargo.toml |
                              jq -r '.packages[] | select(.name == "kalatori") | .version'
                              )" >> $GITHUB_ENV

      - name:                 Draft release binaries
        run:                  >
                              gh release create
                              -d "$VERSION, AH-$AH_VERSION"
                              ./target/release/kalatori
                              ./target/release/kalatori-ah
                              --generate-notes